name: Snap

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  build-amd64:
    runs-on: namespace-profile-ghostty-snap
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache
        uses: namespacelabs/nscloud-cache-action@v1.2.0
        with:
          path: |
            /nix
            /zig
      - run: sudo apt install -y udev
      - run: sudo systemctl start systemd-udevd
      - uses: snapcore/action-build@v1

  build-arm64:
    runs-on: namespace-profile-ghostty-snap-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Setup Cache
        uses: namespacelabs/nscloud-cache-action@v1.2.0
        with:
          path: |
            /nix
            /zig
      - run: sudo apt install -y udev
      - run: sudo systemctl start systemd-udevd
      - uses: snapcore/action-build@v1
